[project]
name = "job-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi[standard]>=0.116.1",
    "lxml>=6.0.0",
    "openai>=1.97.0",
    "pytest-playwright>=0.7.0",
]
